version: '2'

services:
  recept_front:
      container_name: recept_front
      build:
        context: ./front
        args:
          - fotoLocation=${FOTO_LOCATION}
          - templocation=${TEMP_LOCATION}
      env_file:
        - '.env'
      ports:
        - "${NODE_PORT}:${NODE_PORT}"
      depends_on:
        - recept_app
      links:
        - recept_app
      volumes:
        - ./front/fe/actions:/usr/src/app/fe/actions
        - ./front/fe/components:/usr/src/app/fe/components
        - ./front/fe/constants:/usr/src/app/fe/constants
        - ./front/fe/containers:/usr/src/app/fe/containers
        - ./front/fe/reducers:/usr/src/app/fe/reducers
        - ./front/fe/styles:/usr/src/app/fe/styles
        - ./front/fe/svg:/usr/src/app/fe/svg
        - ./front/fe/utils:/usr/src/app/fe/utils
        - ./front/fe/app.js:/usr/src/app/fe/app.js
        - ./front/fe/Store.js:/usr/src/app/fe/Store.js
        - ./front/fe/dev-server.js:/usr/src/app/fe/dev-server.js
        - ./front/fe/bin:/usr/src/app/fe/bin
        - ./front/fe/dependencies:/usr/src/app/fe/dependencies
        - ./front/fe/index.html:/usr/src/app/fe/index.html

#  recept_front_vue:
#        container_name: front_vue
#        build:
#          context: ./front_vue
#          args:
#            - fotoLocation=${FOTO_LOCATION}
#            - templocation=${TEMP_LOCATION}
#        env_file:
#          - '.env'
#        ports:
#          - "${NODE_PORT_VUE}:${NODE_PORT_VUE}"
#        depends_on:
#          - recept_app
#        links:
#          - recept_app
#        volumes:
#          - ./front_vue/fe/src:/usr/src/app/fe/src
#          - ./front_vue/fe/bin:/usr/src/app/fe/bin
#          - ./front_vue/fe/webpack.config.js:/usr/src/app/fe/webpack.config.js

  recept_app:
    container_name: recept_app
    restart: always
    build: ./app
    ports:
      - "${API_PORT}:${API_PORT}"
      - 8000:8000
    depends_on:
      - recept_db
    links:
      - recept_db
    volumes:
       - ./${FOTO_LOCATION}:/usr/local/tomcat/webapps/ROOT/${FOTO_LOCATION}
       - ./${TEMP_LOCATION}:/usr/local/tomcat/webapps/ROOT/${TEMP_LOCATION}
    env_file:
       - '.env'

  recept_db:
    container_name: recept_db
    image: postgres:9.6
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/recept_plain.sql:/docker-entrypoint-initdb.d/recept_plain.sql
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=recept
