version: '2'

services:
#  recept_front:
#      container_name: recept_front
#      build: ./front
#      ports:
#          - "3004:3004"
#      depends_on:
#        - recept_app
#      volumes:
#        - ./front/fe:/usr/src/app/fe

  recept_app:
    container_name: recept_app
    restart: always
    build: ./app
    ports:
      - "8080:8080"

    depends_on:
      - recept_db
#    depends_on:
#        recept_db:
#          condition: service_healthy
    links:
          - recept_db:recept_db
#    volumes:
#      - ./foto:/usr/src/app/foto
#      - ./tempfiles:/usr/src/app/tempfiles

  recept_db:
    container_name: recept_db
    image: postgres:9.6
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
#    healthcheck:
#          test: ["CMD-SHELL", "pg_isready -U postgres"]
#          interval: 30s
#          timeout: 30s
#          retries: 3