version: '2'

services:
  recept_front:
      container_name: recept_front
      build: ./front
      env_file:
        - '.env'
      ports:
        - "${NODE_PORT}:${NODE_PORT}"
      depends_on:
        - recept_app
      volumes:
        - ./front/fe:/usr/src/app/fe

  recept_app:
    container_name: recept_app
    restart: always
    build: ./app
    ports:
      - "${API_PORT}:${API_PORT}"

    depends_on:
      - recept_db
#    links:
#          - recept_db:recept_db
    volumes:
#      - ./foto:/usr/src/app/foto
       - ./${TEMP_LOCATION}:/usr/local/tomcat/webapps/ROOT/${TEMP_LOCATION}
    env_file:
       - '.env'

  recept_db:
    container_name: recept_db
    image: postgres:9.6
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root