export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const REQ_DEPARTMENTS = 'REQ_DEPARTMENTS';

export const SET_RECEPT_LIST = 'SET_RECEPT_LIST';
export const REQ_RECEPT_LIST = 'REQ_RECEPT_LIST';
export const SET_RECEPT = 'SET_RECEPT';
export const REQ_RECEPT = 'REQ_RECEPT';

export const SET_INGRIDIENTS = 'SET_INGRIDIENTS';
export const REQ_INGRIDIENTS = 'REQ_INGRIDIENTS';
export const REQ_ADD_INGRIDIENT = 'REQ_ADD_INGRIDIENT';

export const TOGGLE_ERROR = 'TOGGLE_ERROR';

export const SET_RECEPT_NAME = 'SET_RECEPT_NAME';
export const SET_RECEPT_DEPARTMENT = 'SET_RECEPT_DEPARTMENT';
export const SET_RECEPT_TEXT = 'SET_RECEPT_TEXT';
export const ADD_RECEPT_PROPORTION = 'ADD_RECEPT_PROPORTION';
export const REMOVE_RECEPT_PROPORTION = 'REMOVE_RECEPT_PROPORTION';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const ADD_REF = 'ADD_REF';
export const REMOVE_REF = 'REMOVE_REF';
export const ADD_DETAIL = 'ADD_DETAIL';
export const REMOVE_DETAIL = 'REMOVE_DETAIL';

export const SET_FILE_PATH = 'SET_FILE_PATH';
export const REMOVE_FOTO = 'REMOVE_FOTO';

export const CREATE_RECEPT = 'CREATE_RECEPT';
export const SET_CREATED_RECEPT = 'SET_CREATED_RECEPT';

export const SET_TAGS = 'SET_TAGS';
export const REQ_TAGS = 'REQ_TAGS';


export const COPY_RECEPT = 'COPY_RECEPT';
export const ADD_HEADER_BUTTON = 'ADD_HEADER_BUTTON';
export const REMOVE_HEADER_BUTTON = 'REMOVE_HEADER_BUTTON';


